use_frameworks!

platform :ios, '11.0'

target 'KEPAd_Example' do
  pod 'KEPAd', :path => '../'
  pod 'LKFoundation', :git => 'https://www.github.com/honeyluka/LKFoundation.git'

  target 'KEPAd_Tests' do
    inherit! :search_paths

    
  end
end
